### ISSUE TITLE
Host name is "Default string." Is this usual?

### ISSUE THREAD

**Issue by NexxieIsNotACoder** [caverym/rfetch#2]
Rfetch is great overall, but what bothers me is the host. It says "Default string." My host name should be "hilan", right? Please fix this.
![image](https://user-images.githubusercontent.com/83788509/117364241-45354580-ae83-11eb-89b7-bbdbe08ece9f.png)
I'm on the latest version, if you're wondering about that. 
![image](https://user-images.githubusercontent.com/83788509/117364395-7a419800-ae83-11eb-8071-1bb92284d15b.png)

**Comment by caverym** [comment]
Host and hostname are different. Can you download the source and run a debug executable with the `--debug` flag?

**Comment by NexxieIsNotACoder** [comment]
And how can I do that? Sorry, I'm new to this type of thing.

**Comment by caverym** [comment]
Install Rust. https://rust-lang.org/

Clone the repository

In the directory run `cargo r -- --debug` 

Send the output here in a code block

**Comment by NexxieIsNotACoder** [comment]
```

   Compiling rfetch v0.4.1 (/home/nexi/rfetch)
    Finished dev [unoptimized + debuginfo] target(s) in 1.23s
     Running `target/debug/rfetch --debug`
[src/main.rs:79] self = Rfetch {
    user: Ecos {
        name: Some(
            "nexi",
        ),
        home: Some(
            "/home/nexi",
        ),
        shell: Some(
            "Bash",
        ),
        desktop: Some(
            "GNOME",
        ),
        session: Some(
            "X11",
        ),
        distro: Some(
            "Arch",
        ),
        cpu: Some(
            "AMD Ryzen 5 2600 Six-Core Processor",
        ),
        board: Some(
            "Default string",
        ),
        mem: Some(
            "3781/16007",
        ),
        uptime: Some(
            "18m 44s",
        ),
    },
    uname: Uname {
        sysname: "Linux",
        nodename: "hilan",
        release: "5.11.16-zen1-1-zen",
        version: "#1 ZEN SMP PREEMPT Wed, 21 Apr 2021 17:22:09 +0000",
        machine: "x86_64",
    },
}

```

**Comment by caverym** [comment]
The issue is that the file being read contains "Default string"
